package leetcode;

import java.util.Arrays;

/**
 * 	Given two strings s and t which consist of only lowercase letters.
 * 	
 * 	String t is generated by random shuffling string s and
 * 	then add one more letter at a random position.
 * 	
 * 	Find the letter that was added in t.
 */

public class P389_FindTheDifference {
	/*
	 * 	7 ms
	 */
	static class Solution {
		int[] map1 = new int[26];
		int[] map2 = new int[26];
	    public char findTheDifference(String s, String t) {
	    	Arrays.fill(map1, 0);
	    	Arrays.fill(map2, 0);
	        conMap(s, map1);
	        conMap(t, map2);
	        for (int i = 0; i < 26; i ++)
	        	if (map1[i] != map2[i])
	        		return (char)( 'a' + i);
	        return '\0';
	    }
		private void conMap(String s, int[] map) {
			for (int i = s.length() - 1; i > -1; i --)
				map[s.charAt(i) - 'a'] ++;
		}
	}
}
